import { TimeOption } from '@grafana/data';

export const quickOptions: TimeOption[] = [
  { from: 'now-5m', to: 'now', id: 'datetime-pickers.options.last-5-mins', display: 'Last 5 minutes' },
  { from: 'now-15m', to: 'now', id: 'datetime-pickers.options.last-15-mins', display: 'Last 15 minutes' },
  { from: 'now-30m', to: 'now', id: 'datetime-pickers.options.last-30-mins', display: 'Last 30 minutes' },
  { from: 'now-1h', to: 'now', id: 'datetime-pickers.options.last-1-hour', display: 'Last 1 hour' },
  { from: 'now-3h', to: 'now', id: 'datetime-pickers.options.last-3-hours', display: 'Last 3 hours' },
  { from: 'now-6h', to: 'now', id: 'datetime-pickers.options.last-6-hours', display: 'Last 6 hours' },
  { from: 'now-12h', to: 'now', id: 'datetime-pickers.options.last-12-hours', display: 'Last 12 hours' },
  { from: 'now-24h', to: 'now', id: 'datetime-pickers.options.last-24-hours', display: 'Last 24 hours' },
  { from: 'now-2d', to: 'now', id: 'datetime-pickers.options.last-2-days', display: 'Last 2 days' },
  { from: 'now-7d', to: 'now', id: 'datetime-pickers.options.last-7-days', display: 'Last 7 days' },
  { from: 'now-30d', to: 'now', id: 'datetime-pickers.options.last-30-days', display: 'Last 30 days' },
  { from: 'now-90d', to: 'now', id: 'datetime-pickers.options.last-90-days', display: 'Last 90 days' },
  { from: 'now-6M', to: 'now', id: 'datetime-pickers.options.last-6-months', display: 'Last 6 months' },
  { from: 'now-1y', to: 'now', id: 'datetime-pickers.options.last-1-year', display: 'Last 1 year' },
  { from: 'now-2y', to: 'now', id: 'datetime-pickers.options.last-2-years', display: 'Last 2 years' },
  { from: 'now-5y', to: 'now', id: 'datetime-pickers.options.last-5-years', display: 'Last 5 years' },
  { from: 'now-1d/d', to: 'now-1d/d', id: 'datetime-pickers.options.yesterday', display: 'Yesterday' },
  { from: 'now-2d/d', to: 'now-2d/d', id: 'datetime-pickers.options.day-b-yesterday', display: 'Day before yesterday' },
  { from: 'now-7d/d', to: 'now-7d/d', id: 'datetime-pickers.options.this-day-last-w', display: 'This day last week' },
  { from: 'now-1w/w', to: 'now-1w/w', id: 'datetime-pickers.options.previous-week', display: 'Previous week' },
  { from: 'now-1M/M', to: 'now-1M/M', id: 'datetime-pickers.options.previous-month', display: 'Previous month' },
  {
    from: 'now-1Q/fQ',
    to: 'now-1Q/fQ',
    id: 'datetime-pickers.options.previous-fiscal-quarter',
    display: 'Previous fiscal quarter',
  },
  { from: 'now-1y/y', to: 'now-1y/y', id: 'datetime-pickers.options.previous-year', display: 'Previous year' },
  {
    from: 'now-1y/fy',
    to: 'now-1y/fy',
    id: 'datetime-pickers.options.previous-fiscal-year',
    display: 'Previous fiscal year',
  },
  { from: 'now/d', to: 'now/d', id: 'datetime-pickers.options.today', display: 'Today' },
  { from: 'now/d', to: 'now', id: 'datetime-pickers.options.today-so-far', display: 'Today so far' },
  { from: 'now/w', to: 'now/w', id: 'datetime-pickers.options.this-week', display: 'This week' },
  { from: 'now/w', to: 'now', id: 'datetime-pickers.options.this-week-so-far', display: 'This week so far' },
  { from: 'now/M', to: 'now/M', id: 'datetime-pickers.options.this-month', display: 'This month' },
  { from: 'now/M', to: 'now', id: 'datetime-pickers.options.this-month-so-far', display: 'This month so far' },
  { from: 'now/y', to: 'now/y', id: 'datetime-pickers.options.this-year', display: 'This year' },
  { from: 'now/y', to: 'now', id: 'datetime-pickers.options.this-year-so-far', display: 'This year so far' },
  {
    from: 'now/fQ',
    to: 'now',
    id: 'datetime-pickers.options.this-fiscal-quarter-so-far',
    display: 'This fiscal quarter so far',
  },
  { from: 'now/fQ', to: 'now/fQ', id: 'datetime-pickers.options.this-fiscal-quarter', display: 'This fiscal quarter' },
  {
    from: 'now/fy',
    to: 'now',
    id: 'datetime-pickers.options.this-fiscal-year-so-far',
    display: 'This fiscal year so far',
  },
  { from: 'now/fy', to: 'now/fy', id: 'datetime-pickers.options.this-fiscal-year', display: 'This fiscal year' },
];

export const monthOptions: Array<{ label: string; id: string; value: number }> = [
  { label: 'January', id: 'datetime-pickers.month.january', value: 0 },
  { label: 'February', id: 'datetime-pickers.month.february', value: 1 },
  { label: 'March', id: 'datetime-pickers.month.march', value: 2 },
  { label: 'April', id: 'datetime-pickers.month.april', value: 3 },
  { label: 'May', id: 'datetime-pickers.month.may', value: 4 },
  { label: 'June', id: 'datetime-pickers.month.june', value: 5 },
  { label: 'July', id: 'datetime-pickers.month.july', value: 6 },
  { label: 'August', id: 'datetime-pickers.month.august', value: 7 },
  { label: 'September', id: 'datetime-pickers.month.september', value: 8 },
  { label: 'October', id: 'datetime-pickers.month.october', value: 9 },
  { label: 'November', id: 'datetime-pickers.month.november', value: 10 },
  { label: 'December', id: 'datetime-pickers.month.december', value: 11 },
];
